version: '2.4'

services:
    ctf:
        build: ./
        restart: always
        ports:
            - "30002:30002"
        expose:
            - "30002"
        mem_limit: 100m
        read_only: true
