version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - '36262:36262'
      - '10001:10001'
    volumes:
      - ./writeup/nginx.conf:/etc/nginx/nginx.conf
    links:
      - node-tracker
      - node-seeder
  node-tracker:
    restart: always
    build:
      context: ./writeup
    command: node /plzseed/tracker.js
  node-seeder:
    restart: always
    build:
      context: ./writeup
    command: node /plzseed/seeder.js
